# fly.toml app configuration file generated for rcm-web-wrls-q on 2025-06-23T17:45:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rcm-web-wrls-q'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
